# Path to CAMISIM directory. This is a placeholder, change it the path where your fork of CAMISIM is located
camisim_path: /home/mrahman/magician/CAMISIM
# Conda frontend to use in Snakemake. Use mamba if you have installed this instead.
conda_frontend: mamba

# -----------------------------------------------------------------------------
# GLOBAL OUTPUT
# -----------------------------------------------------------------------------
outdir: ../simulated_data/camisim_toy          # <– NEW location for *all* outputs
dataset_id: CAMISIM_TOY_2                        # <– short tag used in filenames
